### ISSUE TITLE
PGPAP/X-window resize (original issue: Movie mode shortcut stalls Splash)

### ISSUE THREAD

**Issue by markahutch** [danieljprice/giza#18]
The movie mode shortcut no longer works for me. If I press Enter, the page size changes, but nothing appears and I have to force quit Splash.

**Comment by danieljprice** [comment]
I confirm this was caused by 55fb9789

I also confirm that this breaks the PGPAP implementation. For example, pgdemo12 no longer works correctly

**Comment by haavee** [comment]
The X-Window resize is a bit of a problem :-(
Part of this might be alleviated by copying the old pixmap onto the new window so it does not remain blank.
Not sure how the "resizing the PGPLOT window in the background" is to be _properly_ done without an X event loop; I've already spend some time thinking about how to do this.

An idea I had was to make the giza X driver paint to a [recording surface](https://www.cairographics.org/manual/cairo-Recording-Surfaces.html) such that it can be replayed after the window is resized.

**Comment by danieljprice** [comment]
some of this *might* be historical. We did not originally have a working resize implementation, so giza's "PGPAP" had to be called BEFORE the call to giza_open to set the paper size. So this may be an easy fix to restore pgplot-like behaviour by removing the "immediate effect" thing from within Giza's pgpap -- so the page resize does not take effect until the next pgenv call

**Comment by haavee** [comment]
Can someone test this branch https://github.com/haavee/giza/tree/issue-18 ?

I've made a couple of changes in an attempt to be more PGPLOT compatible:
- asking for confirmation now skips the first time (I cheated by looking into PGPLOT source code and add a similar per-device flag + reset of that flag at the same point in the code)
- the code now prompts _before_ creating a new page; before the code would first change to a new page (erasing what's on screen ...) and only then ask "oh, should I have actually done that?" ;-)
- `pgpap()` does _not_ call `giza_change_page()` anymore; it now only updates the bookkeeping in `Dev[id]` and sets the `.resize` flag (which it already did)
- `_giza_change_page_xw()` already handled resizing of the window if, upon entry, the `Dev[id].resize` flag was set. This takes (and took) preference over detecting if someone had changed the size of the XWindow e.g. by dragging with the mouse. Such an event would be picked up on moving to the next page.
- `_giza_change_size_xw()` removed because that one acted immediately, which was (a) not desired and (b) it was never called anyway; the act of physically resizing the XWindow + new surface creation was already handled by the updated `_giza_change_page_xw()` anyway.

`pgdemo12` now works identical for me using PGPLOT or giza

**Comment by markahutch** [comment]
If I checkout the giza branch in the link, I get the following error when I
try to plot a file with Splash:

At line 70 of file ../src/defaults.f90
Internal Error: get_unit(): Bad internal unit KIND

**Comment by danieljprice** [comment]
there's a routine missing, I can't compile the branch
```
Undefined symbols for architecture x86_64:
  "__giza_change_size_xw", referenced from:
      __giza_resize_device in libgiza_la-giza-drivers.o
```

in my source code the routine "giza_change_size_xw" does not exist...

**Comment by haavee** [comment]
Oh bugger. Can you pull my fork and checkout `issue-18` again? There was a function still referencing the removed `_giza_change_size_xw` - should be fixed now.

As to the `src/defaults.f90` I don't see that in the giza source tree. Or is that in Splash? To the best of my knowledge I haven't touched any of the internal unit / pgplot-to-giza unit conversion.

**Comment by markahutch** [comment]
Perhaps I just forgot to 'make clean' first, sorry. I checked out issue-18
again and I still get a hanging white screen when using the movie shortcut.

**Comment by haavee** [comment]
I've just downloaded & built Splash, I'd like to see what's happening. Can you give some details "how to reproduce"? (I've never seen or used Splash, sorry)

**Comment by markahutch** [comment]
Once Splash is built, you just need a file to read. I have attached a small
file that you can use. In the same directory as the file, you should then
be able to type:

ssplash dump_00000

This will bring up the main menu with various quantities you can plot. To
reproduce the blank screen, you will want a rendered plot with which to
start. To do this, you can enter the following values:

2 <Enter>
1 <Enter>
6 <Enter>
<Enter>
<Enter>

You should now have a rendered image with axes and a colourbar. In previous
versions, we could simply hit <Enter> once more and it would automatically
adjust the page size, background colours, and axes which were more suitable
for making videos. However, now if you hit <Enter>, it adjusts the page
size, but it stalls on a blank white background and you have to force quite
Splash to regain control.

**Comment by haavee** [comment]
Hi Mark, thanks! But ... am I looking in the wrong place? Because I don't see an attachment?

**Comment by markahutch** [comment]
I definitely attached the file...perhaps the github server doesn't allow
attachments? Maybe it is easier if I send you the link to the file in my
Dropbox: https://www.dropbox.com/s/ggcmmw250zwxcmb/dump_00000?dl=0
<https://www.dropbox.com/s/ggcmmw250zwxcmb/dump_00000?dl=0>

**Comment by haavee** [comment]
Thanks, got it! It seems that the whole of 'interactive mode' stops working; even typing 'h' doesn't work anymore. But at least now I have something to reproduce+test with!

**Comment by haavee** [comment]
I think I found it. Can you try https://github.com/haavee/giza/tree/issue-18 again?
Don't forget to `git pull` and `make clean && make` ...

I traced it to `_giza_change_page_xw()` waiting for a ConfigureNotify event from the X system after it requests X to resize the window (which is what `PGPAP()` eventually aims to do). That event never arrived ... so it just sat there in an infinite wait, the only escape out of that being the force-quit.

I've removed the wait-for-event and both `pgdemo12` as well as `bin/ssplash dump_0000` now work for me.

**Comment by danieljprice** [comment]
I also confirm this works -- thanks Harro! Will merge.
